version: '3'
services:
  db:
    image: mysql
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: example
        MYSQL_PASSWORD: example
        MYSQL_DATABASE: example